#!/bin/bash

##create the Shell that will send the message every hour
sudo sh -c 'cat > /home/ec2-user/Cmessage.bash' << EF
#!/bin/bash

##numbers of users connected to the machine
Users=$(/usr/bin/who | grep -c "")

##system open in the VM
System=$(uname)

##time in seconds that the machines is on
time=$(cut -f1 -d\ < /proc/uptime)

##message sended to the user by email
message="the machine with system ${System} is ON with ${Users} users logged in"

##condition if there are no users and passed 1 hour send the message
if [ Users -eq 0 ] && [ $time > 3600]; then
	echo "${message}. there is not activity. please stop the VM." | mail -s "report" 18328710948@tmomail.net

else
fi

EF

##introducing the task into the cron file
sudo sh -c 'echo "0 */1 * * * ~/Cmessage.bash" >> /var/spool/cron/ec2-user'

